version: '3.9'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=123;Server=postgres_db;Port=5432;Database=postgres-db; IntegratedSecurity=true; Pooling=true;
    ports:
      - "5000:80"

  client:
    ports:
      - "3000:3000"
    
  proxy:
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
 
  postgres_db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres-db
    ports:
      - "5432:5432"
   
  
